name: 'TriggerJenkinsJob'
description: 'Trigger a Jenkins job from GitHub actions'
inputs:
  urljenkins:
    description: 'The Jenkins Job URL'
    required: true
  urlrepo:
    description: 'The repository URL'
    required: true
  entorno:
    description: 'The environment name'
    required: true
  user:
    description: 'The username for HTTP basic auth'
    required: true
  password:
    description: 'The password (or token) for HTTP basic auth'
    required: true
  rama:
    description: 'The branch'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Setup Node.js environment 
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests
      shell: bash
    - name: Run the script
      run: |
        python jenkins_job2.py ${{ inputs.urljenkins }} ${{ inputs.urlrepo }} ${{ inputs.entorno }} ${{ inputs.user }} ${{ inputs.password }} ${{ inputs.rama  }}
      shell: bash
