name: 'TriggerJenkinsJob'
description: 'Trigger a Jenkins job from GitHub actions'
inputs:
  urljenkins:
    description: 'The Jenkins Job URL'
    required: true
  user:
    description: 'The username for HTTP basic auth'
    required: true
  password:
    description: 'The password (or token) for HTTP basic auth'
    required: true
  job:
    description: 'The Job Name'
    required: true
  params:
    description: 'Job Params'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: juananmora/triggerjenkinsjob
        ref: main
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Setup Node.js environment 
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests argparse jenkinsapi
      shell: bash
    - name: Run the script
      run: |
        python jenkins_job.py ${{ inputs.urljenkins }} ${{ inputs.user }} ${{ inputs.password }} ${{ inputs.job }} '${{ inputs.params  }}'
      shell: bash
